TASK-1
ANS:



NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. It is a fundamental package for scientific computing and data analysis in Python.

Research and write a short explanation aNumPybout.
ANS:

Matrix operations: NumPy supports matrix multiplication, matrix transpose, and other matrix operations.
Data analysis: NumPy provides an efficient way to manipulate and analyze large datasets


TASK-2
ANS:

 Why Use NumPy?
Write a few reasons why NumPy is useful.
ANS:
1. Fast Array Operations: NumPy ki vectorized operations Python lists se zyada tez hain.
2. Optimized C Code: NumPy ka core C mein likha gaya hai, jis se numerical computations mein efficiency milta hai.
1. Multi-Dimensional Arrays: NumPy ka ndarray multi-dimensional arrays ko support karta hai, jis se data analysis aur scientific computing mein madad milta hai.
2. Integration with Other Libraries: NumPy Pandas, Matplotlib, aur Scikit-learn jaise popular libraries ke saath seamlessly integrate hota hai

TASK-3
ANS:

In [1]:
import numpy as np
import time

# Create a large list
list_size = 1000000
my_list = list(range(list_size))

# Create a NumPy array of the same size
my_array = np.arange(list_size)

# Measure time for list operation
start_time = time.time()
result_list = [x**2 for x in my_list]
end_time = time.time()
list_time = end_time - start_time

# Measure time for NumPy array operation
start_time = time.time()
result_array = my_array**2
end_time = time.time()
array_time = end_time - start_time

print(f"List operation time: {list_time:.6f} seconds")
print(f"NumPy array operation time: {array_time:.6f} seconds")

List operation time: 0.086768 seconds
NumPy array operation time: 0.000997 seconds


TASK-4
ANS:

1. C

2. Python

3. Cython

4. Fortran

TASK-5
ANS:

To install Numble using pip, use the following command.

pip install numpy

TASK-6
ANS:

0-Dimensional Array
 (Scalar)

In [2]:

import numpy as np
array_0d = np.array(5)
print(array_0d)

5


1-Dimensional Array (Vector)

In [3]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


2-Dimensional Array (Matrix)

In [4]:
array_2d = np.array([[1, 2], [3, 4]])
print(array_2d)

[[1 2]
 [3 4]]



3-Dimensional Array

In [5]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


TASK-7
ANS:

Copy Functions
- np.copy(): Creates a deep copy of an array

In [6]:
import numpy as np
array = np.array([1, 2, 3])
copy_array = np.copy(array)
print(copy_array)

[1 2 3]



View Functions
- np.view(): Creates a new view of an array.

In [7]:
array = np.array([1, 2, 3])
view_array = array.view()
print(view_array)

[1 2 3]


TASK-8
ANS:

Vertical Stacking
np.vstack((array1, array2))

Horizontal Stacking
np.hstack((array1, array2))


Concatenation
np.concatenate((array1, array2))

In [9]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
joined_array = np.concatenate((array1, array2))
print(joined_array) 

[1 2 3 4 5 6]


TASK-9
ANS:

Vertical Stacking
np.vstack((array1, array2))

Horizontal Stacking
np.hstack((array1, array2))

Depth Stacking
np.dstack((array1, array2))

In [10]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
joined_array = np.vstack((array1, array2))
print(joined_array)

[[1 2 3]
 [4 5 6]]


TASK-10
ANS:


Horizontal Splitting
np.hsplit(array, indices)

Vertical Splitting
np.vsplit(array, indices)

Depth Splitting
np.dsplit(array, indices)

Splitting into Arrays of Equal Size
np.array_split(array, num_subarrays)

In [12]:
import numpy as np
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
split_array = np.hsplit(array, 2)
print(split_array)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


TASK-11
ANS:

- np.where(): 
- np.searchsorted()
- np.argwhere()
- np.nonzero()

In [13]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
indices = np.where(array > 3)
print(indices)

(array([3, 4], dtype=int64),)


DESIRED OUTPUT:

In [14]:
import numpy as np
import time
import copy

# Time taken by list vs NumPy
list_size = 1000000
start_time = time.time()
list_example = list(range(list_size))
end_time = time.time()
list_time = end_time - start_time

start_time = time.time()
array_example = np.arange(list_size)
end_time = time.time()
array_time = end_time - start_time

print(f"Time taken by list: {list_time}")
print(f"Time taken by NumPy: {array_time}")

# Creating arrays of different dimensions
array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D Array: {array_1d}")
print(f"2D Array: {array_2d}")
print(f"3D Array: {array_3d}")

# Copy and view
original_array = np.array([99, 20, 30])
copy_array = copy.copy(original_array)
copy_array[0] = 10
view_array = original_array.view()

print(f"Original: {original_array}")
print(f"Copy: {copy_array}")
print(f"View: {view_array}")

# Joining arrays
joined_array = np.concatenate((np.array([1, 2, 3]), np.array([4, 5, 6])))

print(f"Joined Array: {joined_array}")

# Stacking arrays
stacked_vertically = np.vstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
stacked_horizontally = np.hstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
stacked_depth = np.dstack((np.array([1, 2, 3]), np.array([4, 5, 6])))

print(f"Stacked Vertically: {stacked_vertically}")
print(f"Stacked Horizontally: {stacked_horizontally}")
print(f"Stacked Depth: {stacked_depth}")

# Splitting arrays
split_arrays = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)

print(f"Split Arrays: {split_arrays}")

# Finding index of value in joined_array
index = np.where(joined_array == 3)

print(f"Index of value 3 in joined_array: {index}")

Time taken by list: 0.04351449012756348
Time taken by NumPy: 0.0019958019256591797
1D Array: [1 2 3]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]
Joined Array: [1 2 3 4 5 6]
Stacked Vertically: [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Stacked Depth: [[[1 4]
  [2 5]
  [3 6]]]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]
Index of value 3 in joined_array: (array([2], dtype=int64),)
